# Generated by Django 5.1 on 2025-10-28 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id_avion', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_avion', models.CharField(max_length=255)),
                ('capacidad_pasajeros', models.IntegerField()),
                ('anio_fabricacion', models.IntegerField()),
                ('estado_mantenimiento', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('mantenimiento', 'En Mantenimiento')], default='bueno', max_length=20)),
                ('horas_vuelo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Avión',
                'verbose_name_plural': 'Aviones',
                'ordering': ['modelo_avion'],
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_vuelo', models.CharField(max_length=20, unique=True)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('fecha_hora_salida', models.DateTimeField()),
                ('id_avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='app_vuelos.avion')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['-fecha_hora_salida'],
            },
        ),
    ]
