# Generated by Django 5.1 on 2025-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='aviones/'),
        ),
    ]
